Store canonicalized path in monitors map
Fixes an issue where the source for a given line cannot be found in the
`monitors` map, due to symlinked paths being stored. E.g., on OSX:

```
/Users/jonmagnuson/src/jmagnuson/logtail-dash/target/debug/logtail /var/log/wifi.log
Loading 1 files...
file: /var/log/wifi.log
thread 'main' panicked at 'No monitor for file: /private/var/log/wifi.log', src/bin/logtail-termion.rs:95:9
```